### PR TITLE
Para gerar paginas dinamicas

### PR DESCRIPTION
**Pull request by abbondanza**

### CODE REVIEW

**Comment by jackmakiyama** [comment]
:+1:

**Comment by abbondanza** [comment]
Legal!

**Comment by jackmakiyama** [comment]
Vamos aguardar o pessoal que aceita as PRs agora... =D

**Comment by abbondanza** [comment]
Beleza.. valeu

**Comment by IAMFELIPESOUZA** [comment]
show @abbondanza chegando em casa eu vejo vlw.

**Comment by williamespindola** [comment]
:+1:

**Comment by IAMFELIPESOUZA** [comment]
@abbondanza & @jackmakiyama fiz os testes aqui, funcionou apenas com o http nos cdn's, faça essa change por favor?

**Comment by IAMFELIPESOUZA** [comment]
esquecem eu falei e fiz besteira rsrsrs
thanks guys!

**Comment by abbondanza** [comment]
Rsrs @iamfelipesouza valeu!

On Tuesday, March 24, 2015, Felipe Souza <notifications@github.com> wrote:

> esquecem eu falei e fiz besteira rsrsrs
> thanks guys!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saiadecasa/saiadecasa.github.io/pull/101#issuecomment-85626241>
> .
>


-- 
*Rafael Abbondanza*
(914) 513-1066

*“You have heard that it was said, ‘You shall love your neighbor and hate
your enemy.’ But I say to you, Love your enemies and pray for those who
persecute you."*

*-Jesus; Matthew 5:43-44*

**Comment by abbondanza** [comment]
Se precisarem de alguma coisa, pode entrar em contato comigo

On Tuesday, March 24, 2015, Rafael Abbondanza <abbondanza.r@gmail.com>
wrote:

> Rsrs @iamfelipesouza valeu!
>
> On Tuesday, March 24, 2015, Felipe Souza <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> esquecem eu falei e fiz besteira rsrsrs
>> thanks guys!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/saiadecasa/saiadecasa.github.io/pull/101#issuecomment-85626241>
>> .
>>
>
>
> --
> *Rafael Abbondanza*
> (914) 513-1066
>
> *“You have heard that it was said, ‘You shall love your neighbor and hate
> your enemy.’ But I say to you, Love your enemies and pray for those who
> persecute you."*
>
> *-Jesus; Matthew 5:43-44*
>
>
>

-- 
*Rafael Abbondanza*
(914) 513-1066

*“You have heard that it was said, ‘You shall love your neighbor and hate
your enemy.’ But I say to you, Love your enemies and pray for those who
persecute you."*

*-Jesus; Matthew 5:43-44*

**Comment by IAMFELIPESOUZA** [comment]
demorou @abbondanza.
olha eu subi outra msg de commit, tudo bem?

**Comment by abbondanza** [comment]
@iamfelipesouza .. Sem problema

On Tuesday, March 24, 2015, Felipe Souza <notifications@github.com> wrote:

> demorou @abbondanza <https://github.com/abbondanza>.
> olha eu subi outra msg de commit, tudo bem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/saiadecasa/saiadecasa.github.io/pull/101#issuecomment-85638993>
> .
>


-- 
*Rafael Abbondanza*
(914) 513-1066

*“You have heard that it was said, ‘You shall love your neighbor and hate
your enemy.’ But I say to you, Love your enemies and pray for those who
persecute you."*

*-Jesus; Matthew 5:43-44*

**Comment by hussani** [comment]
Cara, como queria ter feito isso. rs
Valeu @abbondanza !

**Pull request merged**
